version: "3.7"

services:
  dev-db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports: [3306:3306]
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=omdb
    volumes:
      - ./docker-data/mysql:/var/lib/mysql
