version: "3.7"

services:
  dev-db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports: [3306:3306]
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=omdb
    volumes:
      - ./docker-data/mysql:/var/lib/mysql

  old-db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports: [3307:3306]
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=omdb
    volumes:
      - ./docker-data/mysql-old:/var/lib/mysql

  app:
    build: .
    environment:
      - DATABASE_URL=mysql://root:${MYSQL_ROOT_PASSWORD}@prod-db:3306/omdb
    ports: [5000:3000]
    depends_on:
      prod-db:
        condition: service_healthy
    networks:
      - prod

  prod-db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=omdb
    volumes:
      - ./docker-data/mysql-prod:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    networks:
      - prod

networks:
  prod:
